siteTitle = "REACTing to Rust"
siteDescr = "Experiences in React and Rust"
siteAuthor = "Josh Horwitz"

siteTwitterUrl = "http://www.twitter.com/jdhorwitz"
siteGithubUrl = "http://www.github.com/jdhorwitz"
siteEmailUrl = "mailto:jhorwitz@protonmail.ch"

googleAnalyticsId = ""

linkPrefix = "/"
